### ISSUE TITLE
TypeError when using codevalidator on commit

### ISSUE THREAD

**Issue by ehartung** [zalando-bus/turnstile#13]
I have activated the codevalidator commit hook for my repository. Now i am receiving the following error on committing:

```
Traceback (most recent call last):
File "/usr/local/bin/zalando-turnstile-pre-commit", line 9, in <module>
load_entry_point('zalando-turnstile==1.6.1', 'console_scripts', 'zalando-turnstile-pre-commit')()
File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 664, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 644, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 837, in invoke
return ctx.invoke(self.callback, **ctx.params)
File
 "/usr/local/lib/python3.4/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/turnstile/pre_commit.py", line 44, in pre_commit
    failed_checks = checks.run_checks('pre-commit', user_configuration, repository_configuration, staging_area)
  File "/usr/local/lib/python3.4/dist-packages/turnstile/checks/__init__.py", line 121, in run_checks
    result = check(user_configuration, repository_configuration, check_object)
  File "/usr/local/lib/python3.4/dist-packages/turnstile/checks/pre_commit/codevalidator.py", line 101, in check
    custom_config=codevalidator_rc)
  File "/usr/local/lib/python3.4/dist-packages/turnstile/checks/pre_commit/codevalidator.py", line 48, in codevalidator
    codevalidator_output = remove_temporary_path(codevalidator_output, temporary_dir)
  File "/usr/local/lib/python3.4/dist-packages/turnstile/checks/pre_commit/codevalidator.py", line 69, in remove_temporary_path
    lines = [regex.sub('', line, 1) for line in codevalidator_output.splitlines()]
  File "/usr/local/lib/python3.4/dist-packages/turnstile/checks/pre_commit/codevalidator.py", line 69, in <listcomp>
    lines = [regex.sub('', line, 1) for line in codevalidator_output.splitlines()]
TypeError: can't use a string pattern on a bytes-like object
```

My .turnstile.yml looks like this:

```
checks:
    - codevalidator
```

**Comment by jmcs** [comment]
Fixed on release 1.6.2.
